{
  "info": {
    "description": "Endpoints that are not meant to be called externally, and are generally called by the connect widget UI",
    "title": "Internal widget service endpoints",
    "version": "0.1.0"
  },
  "openapi": "3.0.0",
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "servers": [
    {
      "description": "Widget Service",
      "url": "http://localhost:8080"
    }
  ],
  "paths": {
    "/instrumentation/userId/{userId}": {
      "post": {
        "description": "This endpoint is called by the connect widget frontend and returns response headers that are saved for future requests from the connect widget",
        "parameters": [
          {
            "in": "path",
            "name": "userId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "current_aggregator": {
                    "type": "string"
                  },
                  "current_member_guid": {
                    "type": "string"
                  },
                  "jobTypes": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "enum": [
                        "accountNumber",
                        "accountOwner",
                        "transactions",
                        "transactionHistory"
                      ]
                    }
                  },
                  "singleAccountSelect": {
                    "type": "boolean"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "headers": {
              "meta": {
                "schema": {
                  "type": "object",
                  "example": {
                    "userId": "testUserId",
                    "jobTypes": ["transactions"],
                    "scheme": "vcs",
                    "oauth_referral_source": "BROWSER",
                    "singleAccountSelect": true,
                    "updated": true
                  }
                }
              }
            }
          }
        }
      }
    },
    "/institutions/{institutionGuid}": {
      "get": {
        "description": "Get an institution by its aggregator's ID or by the ucp id",
        "parameters": [
          {
            "in": "header",
            "name": "meta",
            "required": true,
            "schema": {
              "type": "object"
            },
            "examples": {
              "byAggregatorInstitutionId": {
                "description": "aggregator is required if sending an aggregator's institution id",
                "value": {
                  "aggregator": "mx"
                }
              },
              "byUCPInstitutionId": {
                "description": "jobTypes is required if sending an UCP institution id",
                "value": {
                  "jobTypes": ["transactions"]
                }
              }
            }
          },
          {
            "description": "Aggregator's institution id or UCP institution id",
            "in": "path",
            "name": "institutionGuid",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "guid": "testExampleA",
                    "code": "testExampleA",
                    "name": "TestExampleA Bank",
                    "url": "https://test-example.com",
                    "logo_url": "https://universalconnectproject.org/images/ucp-logo-icon.svg",
                    "instructional_data": {},
                    "credentials": [],
                    "supports_oauth": false,
                    "aggregator": "testExampleC"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/institutions/{institutionGuid}/credentials": {
      "get": {
        "description": "List of credential objects for the institution. These are used to render authentication inputs",
        "parameters": [
          {
            "in": "header",
            "name": "meta",
            "required": true,
            "schema": {
              "type": "object",
              "example": {
                "aggregator": "mx"
              }
            }
          },
          {
            "in": "path",
            "name": "institutionGuid",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "example": [
                    {
                      "id": "testId",
                      "field_name": "fieldName",
                      "field_type": 3,
                      "label": "TestExampleC Label",
                      "guid": "testId"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/institutions/recommended": {
      "get": {
        "description": "List of recommended institutions",
        "parameters": [
          {
            "in": "header",
            "name": "meta",
            "required": true,
            "schema": {
              "type": "object",
              "example": {
                "jobTypes": ["transactions"]
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "example": [
                    {
                      "guid": "5e498f60-3496-4299-96ed-f8eb328ae8af",
                      "name": "TestExampleA Bank",
                      "url": "https://test-example.com",
                      "logo_url": "https://universalconnectproject.org/images/ucp-logo-icon.svg"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/institutions": {
      "get": {
        "description": "List of institution search results",
        "parameters": [
          {
            "in": "header",
            "name": "meta",
            "required": true,
            "schema": {
              "type": "object",
              "example": {
                "jobTypes": ["transactions"]
              }
            }
          },
          {
            "in": "query",
            "name": "search",
            "description": "Text to be searched. Can't be used with a routingNumber query",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "routingNumber",
            "description": "9 digit institution routing number. Can't be used with a search query",
            "schema": {
              "type": "number",
              "example": 111111111
            }
          },
          {
            "in": "query",
            "name": "page",
            "required": true,
            "schema": {
              "type": "number"
            }
          },
          {
            "in": "query",
            "name": "pageSize",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "example": [
                    {
                      "guid": "5e498f60-3496-4299-96ed-f8eb328ae8af",
                      "name": "TestExampleA Bank",
                      "url": "https://test-example.com",
                      "logo_url": "https://universalconnectproject.org/images/ucp-logo-icon.svg"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/jobs/{jobId}": {
      "get": {
        "description": "Returns a job",
        "parameters": [
          {
            "in": "header",
            "name": "meta",
            "required": true,
            "schema": {
              "type": "object",
              "example": {
                "aggregator": "mx"
              }
            }
          },
          {
            "in": "path",
            "name": "jobId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": { "guid": "testGuid", "job_type": 11 }
                }
              }
            }
          }
        }
      }
    },
    "/members": {
      "get": {
        "description": "Get a member by their connection id and aggregator",
        "parameters": [
          {
            "in": "header",
            "name": "meta",
            "required": true,
            "schema": {
              "type": "object",
              "example": {
                "aggregator": "sophtron",
                "connectionId": "test"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "example": [
                    {
                      "institution_guid": "institutionCode",
                      "guid": "testConnectionId",
                      "connection_status": 0,
                      "most_recent_job_guid": null,
                      "is_oauth": false,
                      "aggregator": "mx",
                      "is_being_aggregated": false,
                      "user_guid": "e07115cc-bbf9-466a-b7db-cdbc9c7cd31b",
                      "mfa": {}
                    }
                  ]
                }
              }
            }
          }
        }
      },
      "post": {
        "description": "Create a connection with an aggregator",
        "parameters": [
          {
            "in": "header",
            "name": "meta",
            "required": true,
            "schema": {
              "type": "object",
              "example": {
                "aggregator": "finicity",
                "jobTypes": ["transactions"]
              }
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "credentials": {
                    "type": "array",
                    "example": [{ "guid": "testGuid", "value": "test" }]
                  },
                  "institution_guid": {
                    "type": "string"
                  },
                  "is_oauth": {
                    "type": "boolean"
                  },
                  "skip_aggregation": {
                    "type": "boolean"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "member": {
                      "institution_guid": "institutionCode",
                      "guid": "testConnectionId",
                      "connection_status": 0,
                      "most_recent_job_guid": null,
                      "is_oauth": false,
                      "aggregator": "testExampleC",
                      "is_being_aggregated": false,
                      "mfa": {}
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/members/{connectionId}": {
      "get": {
        "description": "Get a member by their connection id and aggregator",
        "parameters": [
          {
            "in": "header",
            "name": "meta",
            "required": true,
            "schema": {
              "type": "object",
              "example": {
                "aggregator": "sophtron"
              }
            }
          },
          {
            "in": "path",
            "name": "connectionId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "institution_guid": "institutionCode",
                    "guid": "testConnectionId",
                    "connection_status": 3,
                    "most_recent_job_guid": null,
                    "is_oauth": false,
                    "aggregator": "testExampleC",
                    "is_being_aggregated": false,
                    "postMessageEventData": {
                      "memberConnected": {
                        "aggregator": "mx_int",
                        "member_guid": "MBR-b3b1c287-9dea-447a-83c9-2554d7cfc310",
                        "user_guid": "USR-35223fe6-391d-4d02-9184-55a8fcb0b099"
                      },
                      "memberStatusUpdate": {
                        "aggregator": "mx_int",
                        "member_guid": "MBR-b3b1c287-9dea-447a-83c9-2554d7cfc310",
                        "user_guid": "USR-35223fe6-391d-4d02-9184-55a8fcb0b099",
                        "connection_status": 0
                      }
                    },
                    "user_guid": "e07115cc-bbf9-466a-b7db-cdbc9c7cd31b",
                    "mfa": {
                      "credentials": [
                        {
                          "guid": "CRD-a81b35db-28dd-41ea-aed3-6ec8ef682011",
                          "credential_guid": "CRD-a81b35db-28dd-41ea-aed3-6ec8ef682011",
                          "label": "Please select an account:",
                          "type": 2,
                          "options": [
                            {
                              "guid": "Checking",
                              "label": "Checking",
                              "value": "act-23445745",
                              "credential_guid": "CRD-a81b35db-28dd-41ea-aed3-6ec8ef682011"
                            },
                            {
                              "guid": "Savings",
                              "label": "Savings",
                              "value": "act-352386787",
                              "credential_guid": "CRD-a81b35db-28dd-41ea-aed3-6ec8ef682011"
                            }
                          ]
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/members/{connectionId}/credentials": {
      "get": {
        "description": "Get the credentials for a connection",
        "parameters": [
          {
            "in": "path",
            "name": "connectionId",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "header",
            "name": "meta",
            "required": true,
            "schema": {
              "type": "object",
              "example": {
                "aggregator": "mx",
                "jobTypes": ["transactions"]
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "example": [
                    {
                      "id": "testConnectionId",
                      "field_name": "testFieldName",
                      "field_type": 3,
                      "label": "TestExampleA Label",
                      "guid": "testConnectionId"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  }
}
